{{- define "tethysapp.pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if .Values.tethys }}
      storage: {{ .Values.tethys.workspace_size | quote }}
      {{- end }}
{{- end }}